language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./src ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
