language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./src ./tests

notifications:
  email: false
